version: '3.4'
services:
  hedgehog-app:
    depends_on:
      - liquibase
    build: ./
    ports:
      - 7771:7771
    network_mode: "host"
  db:
    image: "postgres:${POSTGRES_VERSION}"
    volumes:
      - datadb:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    network_mode: "host"
volumes:
  datadb:
    name: postgres-data