version: '3.4'
services:
  db:
    image: "postgres:${POSTGRES_VERSION}"
    volumes:
      - datadb:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
  liquibase:
    image: "webdevops/liquibase:postgres"
    volumes:
      - .:/liquibase
    environment:
      - LIQUIBASE_CHANGELOG=${LIQUIBASE_CHANGELOG}
      - LIQUIBASE_URL=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      - LIQUIBASE_USERNAME=${POSTGRES_USER}
      - LIQUIBASE_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db
volumes:
  datadb:
    name: postgres-data